#!/bin/bash

export UWKGM_BASE_DIR="$(realpath $(dirname $BASH_SOURCE))"

source $UWKGM_BASE_DIR/bin/conf
source $UWKGM_BASE_DIR/conf/uwkgm
source $UWKGM_BASE_DIR/conf/databases

if [[ $1 == api ]]; then
    chmod +x $UWKGM_BASE_DIR/bin/api
    $UWKGM_BASE_DIR/bin/api $@

elif [[ $1 == ui ]]; then
    chmod +x $UWKGM_BASE_DIR/bin/ui
    $UWKGM_BASE_DIR/bin/ui $@

fi
