apiVersion: v1
kind: PersistentVolume
metadata:
  name: uwkgm-mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{UWKGM_KUBE_HOST_PATH}}/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uwkgm-mysql-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: uwkgm-mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: uwkgm-mysql-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwkgm-mysql-deployment
  labels:
    app: uwkgm-mysql-app
spec:
  selector:
    matchLabels:
      app: uwkgm-mysql-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uwkgm-mysql-app
    spec:
      containers:
        - image: mysql:{{UWKGM_MYSQL_VERSION}}
          name: uwkgm-mysql-app
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{UWKGM_MYSQL_PASSWORD}}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: uwkgm-mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: uwkgm-mysql-storage
          persistentVolumeClaim:
            claimName: uwkgm-mysql-claim
