development:
  mysql:
    address: localhost
    port: 3306
  mongo:
    address: localhost
    port: 27017
  virtuoso:
    address: http://localhost
    port: 8890

"development:ext":
  mysql:
    address: localhost
    port: 3306
  mongo:
    address: localhost
    port: 27017
  virtuoso:
    address: localhost
    port: 8890

pre-release:
  mysql:
    address: uwkgm-mysql-service
    port: 3306
  mongo:
    address: uwkgm-mongo-service
    port: 27017
  virtuoso:
    address: http://uwkgm-virtuoso-admin-service
    port: 8890

production:
  mysql:
    address: uwkgm-mysql-service
    port: 3306
  mongo:
    address: uwkgm-mongo-service
    port: 27017
  virtuoso:
    address: http://uwkgm-virtuoso-admin-service
    port: 8890

"pre-release:ext":
  mysql:
    address: uwkgm-mysql-service
    port: 3306
  mongo:
    address: uwkgm-mongo-service
    port: 27017
  virtuoso:
    address: http://uwkgm-virtuoso-admin-service
    port: 8890

"production:ext":
  mysql:
    address: uwkgm-mysql-service
    port: 3306
  mongo:
    address: uwkgm-mongo-service
    port: 27017
  virtuoso:
    address: http://uwkgm-virtuoso-admin-service
    port: 8890
