apiVersion: v1
kind: Service
metadata:
  name: uwkgm-mongo-express-service
spec:
  selector:
    app: uwkgm-mongo-express-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwkgm-mongo-express-deployment
  labels:
    app: uwkgm-mongo-express-app
spec:
  selector:
    matchLabels:
      app: uwkgm-mongo-express-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uwkgm-mongo-express-app
    spec:
      containers:
        - name: uwkgm-mongo-express-app
          image: mongo-express
          ports:
            - containerPort: 80
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "{{UWKGM_MONGO_USERNAME}}"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "{{UWKGM_MONGO_PASSWORD}}"
            - name: ME_CONFIG_MONGODB_SERVER
              value: uwkgm-mongo-service
            - name: VCAP_APP_PORT
              value: "80"
            - name: ME_CONFIG_SITE_BASEURL
              value: /mongo/
