apiVersion: v1
kind: PersistentVolume
metadata:
  name: uwkgm-mongo-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{UWKGM_KUBE_HOST_PATH}}/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uwkgm-mongo-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: uwkgm-mongo-service
spec:
  ports:
  - port: 27017
  selector:
    app: uwkgm-mongo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwkgm-mongo-deployment
  labels:
    app: uwkgm-mongo-app
spec:
  selector:
    matchLabels:
      app: uwkgm-mongo-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uwkgm-mongo-app
    spec:
      containers:
        - image: mongo:{{UWKGM_MONGO_VERSION}}
          name: uwkgm-mongo-app
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{UWKGM_MONGO_USERNAME}}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{UWKGM_MONGO_PASSWORD}}"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: uwkgm-mongo-storage
              mountPath: /data/db
      volumes:
        - name: uwkgm-mongo-storage
          persistentVolumeClaim:
            claimName: uwkgm-mongo-claim
