apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwkgm-spring-deployment
  labels:
    app: uwkgm-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uwkgm-spring-app
  template:
    metadata:
      labels:
        app: uwkgm-spring-app
    spec:
      containers:
      - name: uwkgm-spring-app
        image: "localhost:5000/uwkgm/spring:{{UWKGM_SPRING_VERSION}}"
        ports:
            - containerPort: 80
        resources:
          limits:
            memory: 6Gi
---
apiVersion: v1
kind: Service
metadata:
  name: uwkgm-spring-service
spec:
  selector:
    app: uwkgm-spring-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
