names:
  reserved:
    - "{{core.api.name}}"
    - groups
    - permissions
    - throttles
    - password

fields:
  full:
    exclude:
      - id
      - password

  limited:
    exclude:
      - id
      - is_email_verified
      - is_active
      - is_staff
      - is_superuser
      - password

    read_only:
      - username
      - last_login
      - date_joined
      - groups
      - user_permissions

groups:
  system:
    title: Server components

  user_regular:
    title: Regular user
    description: Subject to rate limits

registration:
  email: "register@{{core.email.domain}}"

  activation:
    subject: "Activation Code for {{core.api.title}} Registration"
    template: "{{$base_dir}}/templates/emails/activation.html"

init:
  superusers:
    - username: root
      password: password
      email: "root@{{core.email.domain}}"

  output:
    path: "{{$base_dir}}/local/accounts/passwords"
