graphs:
  - uri: http://dbpedia.org
    name: dbpedia
    title: DBpedia
    description: 2016-10 dump of DBpedia
    default: true
    label: http://www.w3.org/2000/01/rdf-schema#label
    tags: a

  - uri: http://gpcr.uwkgm.com
    name: gpcr
    title: GPCR
    description: GPCR test graph
    default: false
    label: http://www.w3.org/2000/01/rdf-schema#label
    tags: null
