export const iso_639_1 = [
    ['aa', 'Afar'],
    ['ab', 'Abkhazian'],
    ['ae', 'Avestan'],
    ['af', 'Afrikaans'],
    ['ak', 'Akan'],
    ['am', 'Amharic'],
    ['an', 'Aragonese'],
    ['ar', 'Arabic'],
    ['as', 'Assamese'],
    ['av', 'Avaric'],
    ['ay', 'Aymara'],
    ['az', 'Azerbaijani'],
    ['ba', 'Bashkir'],
    ['be', 'Belarusian'],
    ['bg', 'Bulgarian'],
    ['bh', 'Bihari'],
    ['bi', 'Bislama'],
    ['bm', 'Bambara'],
    ['bn', 'Bengali (Bangla)'],
    ['bo', 'Tibetan'],
    ['br', 'Breton'],
    ['bs', 'Bosnian'],
    ['ca', 'Catalan'],
    ['ce', 'Chechen'],
    ['ch', 'Chamorro'],
    ['co', 'Corsican'],
    ['cr', 'Cree'],
    ['cs', 'Czech'],
    ['cu', 'Old Church Slavonic, Old Bulgarian'],
    ['cv', 'Chuvash'],
    ['cy', 'Welsh'],
    ['da', 'Danish'],
    ['de', 'German'],
    ['dv', 'Divehi, Dhivehi, Maldivian'],
    ['dz', 'Dzongkha'],
    ['ee', 'Ewe'],
    ['el', 'Greek'],
    ['en', 'English'],
    ['eo', 'Esperanto'],
    ['es', 'Spanish'],
    ['et', 'Estonian'],
    ['eu', 'Basque'],
    ['fa', 'Persian (Farsi)'],
    ['ff', 'Fula, Fulah, Pulaar, Pular'],
    ['fi', 'Finnish'],
    ['fj', 'Fijian'],
    ['fo', 'Faroese'],
    ['fr', 'French'],
    ['fy', 'Western Frisian'],
    ['ga', 'Irish'],
    ['gd', 'Gaelic (Scottish)'],
    ['gl', 'Galician'],
    ['gn', 'Guarani'],
    ['gu', 'Gujarati'],
    ['gv', 'Gaelic (Manx)'],
    ['gv', 'Manx'],
    ['ha', 'Hausa'],
    ['he', 'Hebrew'],
    ['hi', 'Hindi'],
    ['ho', 'Hiri Motu'],
    ['hr', 'Croatian'],
    ['ht', 'Haitian Creole'],
    ['hu', 'Hungarian'],
    ['hy', 'Armenian'],
    ['hz', 'Herero'],
    ['ia', 'Interlingua'],
    ['id', 'Indonesian'],
    ['ie', 'Interlingue'],
    ['ig', 'Igbo'],
    ['ii', 'Nuosu'],
    ['ii', 'Sichuan Yi'],
    ['ik', 'Inupiak'],
    ['in', 'Indonesian'],
    ['io', 'Ido'],
    ['is', 'Icelandic'],
    ['it', 'Italian'],
    ['iu', 'Inuktitut'],
    ['ja', 'Japanese'],
    ['ji', 'Yiddish'],
    ['jv', 'Javanese'],
    ['ka', 'Georgian'],
    ['kg', 'Kongo'],
    ['ki', 'Kikuyu'],
    ['kj', 'Kwanyama'],
    ['kk', 'Kazakh'],
    ['kl', 'Greenlandic'],
    ['kl', 'Kalaallisut, Greenlandic'],
    ['km', 'Khmer'],
    ['kn', 'Kannada'],
    ['ko', 'Korean'],
    ['kr', 'Kanuri'],
    ['ks', 'Kashmiri'],
    ['ku', 'Kurdish'],
    ['kv', 'Komi'],
    ['kw', 'Cornish'],
    ['ky', 'Kyrgyz'],
    ['la', 'Latin'],
    ['lb', 'Luxembourgish'],
    ['lg', 'Luganda, Ganda'],
    ['li', 'Limburgish ( Limburger)'],
    ['ln', 'Lingala'],
    ['lo', 'Lao'],
    ['lt', 'Lithuanian'],
    ['lu', 'Luga-Katanga'],
    ['lv', 'Latvian (Lettish)'],
    ['mg', 'Malagasy'],
    ['mh', 'Marshallese'],
    ['mi', 'Maori'],
    ['mk', 'Macedonian'],
    ['ml', 'Malayalam'],
    ['mn', 'Mongolian'],
    ['mo', 'Moldavian'],
    ['mr', 'Marathi'],
    ['ms', 'Malay'],
    ['mt', 'Maltese'],
    ['my', 'Burmese'],
    ['na', 'Nauru'],
    ['nb', 'Norwegian bokmål'],
    ['nd', 'Northern Ndebele'],
    ['ne', 'Nepali'],
    ['ng', 'Ndonga'],
    ['nl', 'Dutch'],
    ['nn', 'Norwegian nynorsk'],
    ['no', 'Norwegian'],
    ['nr', 'Southern Ndebele'],
    ['nv', 'Navajo'],
    ['ny', 'Chichewa, Chewa, Nyanja'],
    ['oc', 'Occitan'],
    ['oj', 'Ojibwe'],
    ['om', 'Oromo (Afaan Oromo)'],
    ['or', 'Oriya'],
    ['os', 'Ossetian'],
    ['pa', 'Punjabi (Eastern)'],
    ['pi', 'Pāli'],
    ['pl', 'Polish'],
    ['ps', 'Pashto, Pushto'],
    ['pt', 'Portuguese'],
    ['qu', 'Quechua'],
    ['rm', 'Romansh'],
    ['rn', 'Kirundi'],
    ['ro', 'Romanian'],
    ['ru', 'Russian'],
    ['rw', 'Kinyarwanda (Rwanda)'],
    ['sa', 'Sanskrit'],
    ['sd', 'Sindhi'],
    ['se', 'Sami'],
    ['sg', 'Sango'],
    ['sh', 'Serbo-Croatian'],
    ['si', 'Sinhalese'],
    ['sk', 'Slovak'],
    ['sl', 'Slovenian'],
    ['sm', 'Samoan'],
    ['sn', 'Shona'],
    ['so', 'Somali'],
    ['sq', 'Albanian'],
    ['sr', 'Serbian'],
    ['ss', 'Siswati'],
    ['ss', 'Swati'],
    ['st', 'Sesotho'],
    ['su', 'Sundanese'],
    ['sv', 'Swedish'],
    ['sw', 'Swahili (Kiswahili)'],
    ['ta', 'Tamil'],
    ['te', 'Telugu'],
    ['tg', 'Tajik'],
    ['th', 'Thai'],
    ['ti', 'Tigrinya'],
    ['tk', 'Turkmen'],
    ['tl', 'Tagalog'],
    ['tn', 'Setswana'],
    ['to', 'Tonga'],
    ['tr', 'Turkish'],
    ['ts', 'Tsonga'],
    ['tt', 'Tatar'],
    ['tw', 'Twi'],
    ['ty', 'Tahitian'],
    ['ug', 'Uyghur'],
    ['uk', 'Ukrainian'],
    ['ur', 'Urdu'],
    ['uz', 'Uzbek'],
    ['ve', 'Venda'],
    ['vi', 'Vietnamese'],
    ['vo', 'Volapük'],
    ['wa', 'Wallon'],
    ['wo', 'Wolof'],
    ['xh', 'Xhosa'],
    ['yi', 'Yiddish'],
    ['yo', 'Yoruba'],
    ['za', 'Zhuang, Chuang'],
    ['zh', 'Chinese'],
    ['zh-Hans', 'Chinese (Simplified)'],
    ['zh-Hant', 'Chinese (Traditional)'],
    ['zu', 'Zulu']
];
