apiVersion: v1
kind: PersistentVolume
metadata:
  name: uwkgm-api-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{UWKGM_KUBE_HOST_PATH}}/api/local"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uwkgm-api-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwkgm-api-deployment
  labels:
    app: uwkgm-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uwkgm-api-app
  template:
    metadata:
      labels:
        app: uwkgm-api-app
    spec:
      containers:
        - name: uwkgm-api-app
          image: "localhost:5000/uwkgm/api:{{UWKGM_API_VERSION}}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: uwkgm-api-storage
              mountPath: /uwkgm/local
      volumes:
        - name: uwkgm-api-storage
          persistentVolumeClaim:
            claimName: uwkgm-api-claim
---
apiVersion: v1
kind: Service
metadata:
  name: uwkgm-api-service
spec:
  selector:
    app: uwkgm-api-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
